/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apismultiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	versioned "github.com/multiovn/multi-ovn/pkg/client/clientset/versioned"
	internalinterfaces "github.com/multiovn/multi-ovn/pkg/client/informers/externalversions/internalinterfaces"
	multiovnv1 "github.com/multiovn/multi-ovn/pkg/client/listers/multiovn/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ChassisInformer provides access to a shared informer and lister for
// Chassises.
type ChassisInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() multiovnv1.ChassisLister
}

type chassisInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewChassisInformer constructs a new informer for Chassis type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewChassisInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredChassisInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredChassisInformer constructs a new informer for Chassis type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredChassisInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MultiovnV1().Chassises().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MultiovnV1().Chassises().Watch(context.TODO(), options)
			},
		},
		&apismultiovnv1.Chassis{},
		resyncPeriod,
		indexers,
	)
}

func (f *chassisInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredChassisInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *chassisInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apismultiovnv1.Chassis{}, f.defaultInformer)
}

func (f *chassisInformer) Lister() multiovnv1.ChassisLister {
	return multiovnv1.NewChassisLister(f.Informer().GetIndexer())
}
