/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/multiovn/multi-ovn/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ACLs returns a ACLInformer.
	ACLs() ACLInformer
	// Chassises returns a ChassisInformer.
	Chassises() ChassisInformer
	// HAChassises returns a HAChassisInformer.
	HAChassises() HAChassisInformer
	// HAChassisGroups returns a HAChassisGroupInformer.
	HAChassisGroups() HAChassisGroupInformer
	// LogicalRouters returns a LogicalRouterInformer.
	LogicalRouters() LogicalRouterInformer
	// LogicalRouterPorts returns a LogicalRouterPortInformer.
	LogicalRouterPorts() LogicalRouterPortInformer
	// LogicalSwitches returns a LogicalSwitchInformer.
	LogicalSwitches() LogicalSwitchInformer
	// LogicalSwitchPorts returns a LogicalSwitchPortInformer.
	LogicalSwitchPorts() LogicalSwitchPortInformer
	// Nats returns a NatInformer.
	Nats() NatInformer
	// Ports returns a PortInformer.
	Ports() PortInformer
	// PortGroups returns a PortGroupInformer.
	PortGroups() PortGroupInformer
	// PortGroupPorts returns a PortGroupPortInformer.
	PortGroupPorts() PortGroupPortInformer
	// UserDefinedNetworks returns a UserDefinedNetworkInformer.
	UserDefinedNetworks() UserDefinedNetworkInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ACLs returns a ACLInformer.
func (v *version) ACLs() ACLInformer {
	return &aCLInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Chassises returns a ChassisInformer.
func (v *version) Chassises() ChassisInformer {
	return &chassisInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// HAChassises returns a HAChassisInformer.
func (v *version) HAChassises() HAChassisInformer {
	return &hAChassisInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// HAChassisGroups returns a HAChassisGroupInformer.
func (v *version) HAChassisGroups() HAChassisGroupInformer {
	return &hAChassisGroupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LogicalRouters returns a LogicalRouterInformer.
func (v *version) LogicalRouters() LogicalRouterInformer {
	return &logicalRouterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LogicalRouterPorts returns a LogicalRouterPortInformer.
func (v *version) LogicalRouterPorts() LogicalRouterPortInformer {
	return &logicalRouterPortInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LogicalSwitches returns a LogicalSwitchInformer.
func (v *version) LogicalSwitches() LogicalSwitchInformer {
	return &logicalSwitchInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LogicalSwitchPorts returns a LogicalSwitchPortInformer.
func (v *version) LogicalSwitchPorts() LogicalSwitchPortInformer {
	return &logicalSwitchPortInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Nats returns a NatInformer.
func (v *version) Nats() NatInformer {
	return &natInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Ports returns a PortInformer.
func (v *version) Ports() PortInformer {
	return &portInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// PortGroups returns a PortGroupInformer.
func (v *version) PortGroups() PortGroupInformer {
	return &portGroupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// PortGroupPorts returns a PortGroupPortInformer.
func (v *version) PortGroupPorts() PortGroupPortInformer {
	return &portGroupPortInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// UserDefinedNetworks returns a UserDefinedNetworkInformer.
func (v *version) UserDefinedNetworks() UserDefinedNetworkInformer {
	return &userDefinedNetworkInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
