/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apismultiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	versioned "github.com/multiovn/multi-ovn/pkg/client/clientset/versioned"
	internalinterfaces "github.com/multiovn/multi-ovn/pkg/client/informers/externalversions/internalinterfaces"
	multiovnv1 "github.com/multiovn/multi-ovn/pkg/client/listers/multiovn/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NatInformer provides access to a shared informer and lister for
// Nats.
type NatInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() multiovnv1.NatLister
}

type natInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNatInformer constructs a new informer for Nat type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNatInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNatInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNatInformer constructs a new informer for Nat type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNatInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MultiovnV1().Nats(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MultiovnV1().Nats(namespace).Watch(context.TODO(), options)
			},
		},
		&apismultiovnv1.Nat{},
		resyncPeriod,
		indexers,
	)
}

func (f *natInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNatInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *natInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apismultiovnv1.Nat{}, f.defaultInformer)
}

func (f *natInformer) Lister() multiovnv1.NatLister {
	return multiovnv1.NewNatLister(f.Informer().GetIndexer())
}
