/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/multiovn/multi-ovn/pkg/client/clientset/versioned/typed/multiovn/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMultiovnV1 struct {
	*testing.Fake
}

func (c *FakeMultiovnV1) ACLs(namespace string) v1.ACLInterface {
	return newFakeACLs(c, namespace)
}

func (c *FakeMultiovnV1) Chassises() v1.ChassisInterface {
	return newFakeChassises(c)
}

func (c *FakeMultiovnV1) HAChassises(namespace string) v1.HAChassisInterface {
	return newFakeHAChassises(c, namespace)
}

func (c *FakeMultiovnV1) HAChassisGroups(namespace string) v1.HAChassisGroupInterface {
	return newFakeHAChassisGroups(c, namespace)
}

func (c *FakeMultiovnV1) LogicalRouters(namespace string) v1.LogicalRouterInterface {
	return newFakeLogicalRouters(c, namespace)
}

func (c *FakeMultiovnV1) LogicalRouterPorts(namespace string) v1.LogicalRouterPortInterface {
	return newFakeLogicalRouterPorts(c, namespace)
}

func (c *FakeMultiovnV1) LogicalSwitches(namespace string) v1.LogicalSwitchInterface {
	return newFakeLogicalSwitches(c, namespace)
}

func (c *FakeMultiovnV1) LogicalSwitchPorts(namespace string) v1.LogicalSwitchPortInterface {
	return newFakeLogicalSwitchPorts(c, namespace)
}

func (c *FakeMultiovnV1) Nats(namespace string) v1.NatInterface {
	return newFakeNats(c, namespace)
}

func (c *FakeMultiovnV1) Ports(namespace string) v1.PortInterface {
	return newFakePorts(c, namespace)
}

func (c *FakeMultiovnV1) PortGroups(namespace string) v1.PortGroupInterface {
	return newFakePortGroups(c, namespace)
}

func (c *FakeMultiovnV1) PortGroupPorts(namespace string) v1.PortGroupPortInterface {
	return newFakePortGroupPorts(c, namespace)
}

func (c *FakeMultiovnV1) UserDefinedNetworks(namespace string) v1.UserDefinedNetworkInterface {
	return newFakeUserDefinedNetworks(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMultiovnV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
