/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	scheme "github.com/multiovn/multi-ovn/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ChassisesGetter has a method to return a ChassisInterface.
// A group's client should implement this interface.
type ChassisesGetter interface {
	Chassises() ChassisInterface
}

// ChassisInterface has methods to work with Chassis resources.
type ChassisInterface interface {
	Create(ctx context.Context, chassis *multiovnv1.Chassis, opts metav1.CreateOptions) (*multiovnv1.Chassis, error)
	Update(ctx context.Context, chassis *multiovnv1.Chassis, opts metav1.UpdateOptions) (*multiovnv1.Chassis, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, chassis *multiovnv1.Chassis, opts metav1.UpdateOptions) (*multiovnv1.Chassis, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*multiovnv1.Chassis, error)
	List(ctx context.Context, opts metav1.ListOptions) (*multiovnv1.ChassisList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *multiovnv1.Chassis, err error)
	ChassisExpansion
}

// chassises implements ChassisInterface
type chassises struct {
	*gentype.ClientWithList[*multiovnv1.Chassis, *multiovnv1.ChassisList]
}

// newChassises returns a Chassises
func newChassises(c *MultiovnV1Client) *chassises {
	return &chassises{
		gentype.NewClientWithList[*multiovnv1.Chassis, *multiovnv1.ChassisList](
			"chassises",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *multiovnv1.Chassis { return &multiovnv1.Chassis{} },
			func() *multiovnv1.ChassisList { return &multiovnv1.ChassisList{} },
		),
	}
}
