/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	scheme "github.com/multiovn/multi-ovn/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// HAChassisGroupsGetter has a method to return a HAChassisGroupInterface.
// A group's client should implement this interface.
type HAChassisGroupsGetter interface {
	HAChassisGroups(namespace string) HAChassisGroupInterface
}

// HAChassisGroupInterface has methods to work with HAChassisGroup resources.
type HAChassisGroupInterface interface {
	Create(ctx context.Context, hAChassisGroup *multiovnv1.HAChassisGroup, opts metav1.CreateOptions) (*multiovnv1.HAChassisGroup, error)
	Update(ctx context.Context, hAChassisGroup *multiovnv1.HAChassisGroup, opts metav1.UpdateOptions) (*multiovnv1.HAChassisGroup, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, hAChassisGroup *multiovnv1.HAChassisGroup, opts metav1.UpdateOptions) (*multiovnv1.HAChassisGroup, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*multiovnv1.HAChassisGroup, error)
	List(ctx context.Context, opts metav1.ListOptions) (*multiovnv1.HAChassisGroupList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *multiovnv1.HAChassisGroup, err error)
	HAChassisGroupExpansion
}

// hAChassisGroups implements HAChassisGroupInterface
type hAChassisGroups struct {
	*gentype.ClientWithList[*multiovnv1.HAChassisGroup, *multiovnv1.HAChassisGroupList]
}

// newHAChassisGroups returns a HAChassisGroups
func newHAChassisGroups(c *MultiovnV1Client, namespace string) *hAChassisGroups {
	return &hAChassisGroups{
		gentype.NewClientWithList[*multiovnv1.HAChassisGroup, *multiovnv1.HAChassisGroupList](
			"hachassisgroups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *multiovnv1.HAChassisGroup { return &multiovnv1.HAChassisGroup{} },
			func() *multiovnv1.HAChassisGroupList { return &multiovnv1.HAChassisGroupList{} },
		),
	}
}
