/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	scheme "github.com/multiovn/multi-ovn/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LogicalSwitchPortsGetter has a method to return a LogicalSwitchPortInterface.
// A group's client should implement this interface.
type LogicalSwitchPortsGetter interface {
	LogicalSwitchPorts(namespace string) LogicalSwitchPortInterface
}

// LogicalSwitchPortInterface has methods to work with LogicalSwitchPort resources.
type LogicalSwitchPortInterface interface {
	Create(ctx context.Context, logicalSwitchPort *multiovnv1.LogicalSwitchPort, opts metav1.CreateOptions) (*multiovnv1.LogicalSwitchPort, error)
	Update(ctx context.Context, logicalSwitchPort *multiovnv1.LogicalSwitchPort, opts metav1.UpdateOptions) (*multiovnv1.LogicalSwitchPort, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, logicalSwitchPort *multiovnv1.LogicalSwitchPort, opts metav1.UpdateOptions) (*multiovnv1.LogicalSwitchPort, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*multiovnv1.LogicalSwitchPort, error)
	List(ctx context.Context, opts metav1.ListOptions) (*multiovnv1.LogicalSwitchPortList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *multiovnv1.LogicalSwitchPort, err error)
	LogicalSwitchPortExpansion
}

// logicalSwitchPorts implements LogicalSwitchPortInterface
type logicalSwitchPorts struct {
	*gentype.ClientWithList[*multiovnv1.LogicalSwitchPort, *multiovnv1.LogicalSwitchPortList]
}

// newLogicalSwitchPorts returns a LogicalSwitchPorts
func newLogicalSwitchPorts(c *MultiovnV1Client, namespace string) *logicalSwitchPorts {
	return &logicalSwitchPorts{
		gentype.NewClientWithList[*multiovnv1.LogicalSwitchPort, *multiovnv1.LogicalSwitchPortList](
			"logicalswitchports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *multiovnv1.LogicalSwitchPort { return &multiovnv1.LogicalSwitchPort{} },
			func() *multiovnv1.LogicalSwitchPortList { return &multiovnv1.LogicalSwitchPortList{} },
		),
	}
}
