/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	http "net/http"

	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	scheme "github.com/multiovn/multi-ovn/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type MultiovnV1Interface interface {
	RESTClient() rest.Interface
	ACLsGetter
	ChassisesGetter
	HAChassisesGetter
	HAChassisGroupsGetter
	LogicalRoutersGetter
	LogicalRouterPortsGetter
	LogicalSwitchesGetter
	LogicalSwitchPortsGetter
	NatsGetter
	PortsGetter
	PortGroupsGetter
	PortGroupPortsGetter
	UserDefinedNetworksGetter
}

// MultiovnV1Client is used to interact with features provided by the multiovn.io group.
type MultiovnV1Client struct {
	restClient rest.Interface
}

func (c *MultiovnV1Client) ACLs(namespace string) ACLInterface {
	return newACLs(c, namespace)
}

func (c *MultiovnV1Client) Chassises() ChassisInterface {
	return newChassises(c)
}

func (c *MultiovnV1Client) HAChassises(namespace string) HAChassisInterface {
	return newHAChassises(c, namespace)
}

func (c *MultiovnV1Client) HAChassisGroups(namespace string) HAChassisGroupInterface {
	return newHAChassisGroups(c, namespace)
}

func (c *MultiovnV1Client) LogicalRouters(namespace string) LogicalRouterInterface {
	return newLogicalRouters(c, namespace)
}

func (c *MultiovnV1Client) LogicalRouterPorts(namespace string) LogicalRouterPortInterface {
	return newLogicalRouterPorts(c, namespace)
}

func (c *MultiovnV1Client) LogicalSwitches(namespace string) LogicalSwitchInterface {
	return newLogicalSwitches(c, namespace)
}

func (c *MultiovnV1Client) LogicalSwitchPorts(namespace string) LogicalSwitchPortInterface {
	return newLogicalSwitchPorts(c, namespace)
}

func (c *MultiovnV1Client) Nats(namespace string) NatInterface {
	return newNats(c, namespace)
}

func (c *MultiovnV1Client) Ports(namespace string) PortInterface {
	return newPorts(c, namespace)
}

func (c *MultiovnV1Client) PortGroups(namespace string) PortGroupInterface {
	return newPortGroups(c, namespace)
}

func (c *MultiovnV1Client) PortGroupPorts(namespace string) PortGroupPortInterface {
	return newPortGroupPorts(c, namespace)
}

func (c *MultiovnV1Client) UserDefinedNetworks(namespace string) UserDefinedNetworkInterface {
	return newUserDefinedNetworks(c, namespace)
}

// NewForConfig creates a new MultiovnV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*MultiovnV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new MultiovnV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*MultiovnV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &MultiovnV1Client{client}, nil
}

// NewForConfigOrDie creates a new MultiovnV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *MultiovnV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new MultiovnV1Client for the given RESTClient.
func New(c rest.Interface) *MultiovnV1Client {
	return &MultiovnV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := multiovnv1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *MultiovnV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
