/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	scheme "github.com/multiovn/multi-ovn/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PortsGetter has a method to return a PortInterface.
// A group's client should implement this interface.
type PortsGetter interface {
	Ports(namespace string) PortInterface
}

// PortInterface has methods to work with Port resources.
type PortInterface interface {
	Create(ctx context.Context, port *multiovnv1.Port, opts metav1.CreateOptions) (*multiovnv1.Port, error)
	Update(ctx context.Context, port *multiovnv1.Port, opts metav1.UpdateOptions) (*multiovnv1.Port, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, port *multiovnv1.Port, opts metav1.UpdateOptions) (*multiovnv1.Port, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*multiovnv1.Port, error)
	List(ctx context.Context, opts metav1.ListOptions) (*multiovnv1.PortList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *multiovnv1.Port, err error)
	PortExpansion
}

// ports implements PortInterface
type ports struct {
	*gentype.ClientWithList[*multiovnv1.Port, *multiovnv1.PortList]
}

// newPorts returns a Ports
func newPorts(c *MultiovnV1Client, namespace string) *ports {
	return &ports{
		gentype.NewClientWithList[*multiovnv1.Port, *multiovnv1.PortList](
			"ports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *multiovnv1.Port { return &multiovnv1.Port{} },
			func() *multiovnv1.PortList { return &multiovnv1.PortList{} },
		),
	}
}
