/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	scheme "github.com/multiovn/multi-ovn/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PortGroupPortsGetter has a method to return a PortGroupPortInterface.
// A group's client should implement this interface.
type PortGroupPortsGetter interface {
	PortGroupPorts(namespace string) PortGroupPortInterface
}

// PortGroupPortInterface has methods to work with PortGroupPort resources.
type PortGroupPortInterface interface {
	Create(ctx context.Context, portGroupPort *multiovnv1.PortGroupPort, opts metav1.CreateOptions) (*multiovnv1.PortGroupPort, error)
	Update(ctx context.Context, portGroupPort *multiovnv1.PortGroupPort, opts metav1.UpdateOptions) (*multiovnv1.PortGroupPort, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, portGroupPort *multiovnv1.PortGroupPort, opts metav1.UpdateOptions) (*multiovnv1.PortGroupPort, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*multiovnv1.PortGroupPort, error)
	List(ctx context.Context, opts metav1.ListOptions) (*multiovnv1.PortGroupPortList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *multiovnv1.PortGroupPort, err error)
	PortGroupPortExpansion
}

// portGroupPorts implements PortGroupPortInterface
type portGroupPorts struct {
	*gentype.ClientWithList[*multiovnv1.PortGroupPort, *multiovnv1.PortGroupPortList]
}

// newPortGroupPorts returns a PortGroupPorts
func newPortGroupPorts(c *MultiovnV1Client, namespace string) *portGroupPorts {
	return &portGroupPorts{
		gentype.NewClientWithList[*multiovnv1.PortGroupPort, *multiovnv1.PortGroupPortList](
			"portgroupports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *multiovnv1.PortGroupPort { return &multiovnv1.PortGroupPort{} },
			func() *multiovnv1.PortGroupPortList { return &multiovnv1.PortGroupPortList{} },
		),
	}
}
