/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ACLLister helps list ACLs.
// All objects returned here must be treated as read-only.
type ACLLister interface {
	// List lists all ACLs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.ACL, err error)
	// ACLs returns an object that can list and get ACLs.
	ACLs(namespace string) ACLNamespaceLister
	ACLListerExpansion
}

// aCLLister implements the ACLLister interface.
type aCLLister struct {
	listers.ResourceIndexer[*multiovnv1.ACL]
}

// NewACLLister returns a new ACLLister.
func NewACLLister(indexer cache.Indexer) ACLLister {
	return &aCLLister{listers.New[*multiovnv1.ACL](indexer, multiovnv1.Resource("acl"))}
}

// ACLs returns an object that can list and get ACLs.
func (s *aCLLister) ACLs(namespace string) ACLNamespaceLister {
	return aCLNamespaceLister{listers.NewNamespaced[*multiovnv1.ACL](s.ResourceIndexer, namespace)}
}

// ACLNamespaceLister helps list and get ACLs.
// All objects returned here must be treated as read-only.
type ACLNamespaceLister interface {
	// List lists all ACLs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.ACL, err error)
	// Get retrieves the ACL from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*multiovnv1.ACL, error)
	ACLNamespaceListerExpansion
}

// aCLNamespaceLister implements the ACLNamespaceLister
// interface.
type aCLNamespaceLister struct {
	listers.ResourceIndexer[*multiovnv1.ACL]
}
