/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

// ACLListerExpansion allows custom methods to be added to
// ACLLister.
type ACLListerExpansion interface{}

// ACLNamespaceListerExpansion allows custom methods to be added to
// ACLNamespaceLister.
type ACLNamespaceListerExpansion interface{}

// ChassisListerExpansion allows custom methods to be added to
// ChassisLister.
type ChassisListerExpansion interface{}

// HAChassisListerExpansion allows custom methods to be added to
// HAChassisLister.
type HAChassisListerExpansion interface{}

// HAChassisNamespaceListerExpansion allows custom methods to be added to
// HAChassisNamespaceLister.
type HAChassisNamespaceListerExpansion interface{}

// HAChassisGroupListerExpansion allows custom methods to be added to
// HAChassisGroupLister.
type HAChassisGroupListerExpansion interface{}

// HAChassisGroupNamespaceListerExpansion allows custom methods to be added to
// HAChassisGroupNamespaceLister.
type HAChassisGroupNamespaceListerExpansion interface{}

// LogicalRouterListerExpansion allows custom methods to be added to
// LogicalRouterLister.
type LogicalRouterListerExpansion interface{}

// LogicalRouterNamespaceListerExpansion allows custom methods to be added to
// LogicalRouterNamespaceLister.
type LogicalRouterNamespaceListerExpansion interface{}

// LogicalRouterPortListerExpansion allows custom methods to be added to
// LogicalRouterPortLister.
type LogicalRouterPortListerExpansion interface{}

// LogicalRouterPortNamespaceListerExpansion allows custom methods to be added to
// LogicalRouterPortNamespaceLister.
type LogicalRouterPortNamespaceListerExpansion interface{}

// LogicalSwitchListerExpansion allows custom methods to be added to
// LogicalSwitchLister.
type LogicalSwitchListerExpansion interface{}

// LogicalSwitchNamespaceListerExpansion allows custom methods to be added to
// LogicalSwitchNamespaceLister.
type LogicalSwitchNamespaceListerExpansion interface{}

// LogicalSwitchPortListerExpansion allows custom methods to be added to
// LogicalSwitchPortLister.
type LogicalSwitchPortListerExpansion interface{}

// LogicalSwitchPortNamespaceListerExpansion allows custom methods to be added to
// LogicalSwitchPortNamespaceLister.
type LogicalSwitchPortNamespaceListerExpansion interface{}

// NatListerExpansion allows custom methods to be added to
// NatLister.
type NatListerExpansion interface{}

// NatNamespaceListerExpansion allows custom methods to be added to
// NatNamespaceLister.
type NatNamespaceListerExpansion interface{}

// PortListerExpansion allows custom methods to be added to
// PortLister.
type PortListerExpansion interface{}

// PortNamespaceListerExpansion allows custom methods to be added to
// PortNamespaceLister.
type PortNamespaceListerExpansion interface{}

// PortGroupListerExpansion allows custom methods to be added to
// PortGroupLister.
type PortGroupListerExpansion interface{}

// PortGroupNamespaceListerExpansion allows custom methods to be added to
// PortGroupNamespaceLister.
type PortGroupNamespaceListerExpansion interface{}

// PortGroupPortListerExpansion allows custom methods to be added to
// PortGroupPortLister.
type PortGroupPortListerExpansion interface{}

// PortGroupPortNamespaceListerExpansion allows custom methods to be added to
// PortGroupPortNamespaceLister.
type PortGroupPortNamespaceListerExpansion interface{}

// UserDefinedNetworkListerExpansion allows custom methods to be added to
// UserDefinedNetworkLister.
type UserDefinedNetworkListerExpansion interface{}

// UserDefinedNetworkNamespaceListerExpansion allows custom methods to be added to
// UserDefinedNetworkNamespaceLister.
type UserDefinedNetworkNamespaceListerExpansion interface{}
