/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// HAChassisGroupLister helps list HAChassisGroups.
// All objects returned here must be treated as read-only.
type HAChassisGroupLister interface {
	// List lists all HAChassisGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.HAChassisGroup, err error)
	// HAChassisGroups returns an object that can list and get HAChassisGroups.
	HAChassisGroups(namespace string) HAChassisGroupNamespaceLister
	HAChassisGroupListerExpansion
}

// hAChassisGroupLister implements the HAChassisGroupLister interface.
type hAChassisGroupLister struct {
	listers.ResourceIndexer[*multiovnv1.HAChassisGroup]
}

// NewHAChassisGroupLister returns a new HAChassisGroupLister.
func NewHAChassisGroupLister(indexer cache.Indexer) HAChassisGroupLister {
	return &hAChassisGroupLister{listers.New[*multiovnv1.HAChassisGroup](indexer, multiovnv1.Resource("hachassisgroup"))}
}

// HAChassisGroups returns an object that can list and get HAChassisGroups.
func (s *hAChassisGroupLister) HAChassisGroups(namespace string) HAChassisGroupNamespaceLister {
	return hAChassisGroupNamespaceLister{listers.NewNamespaced[*multiovnv1.HAChassisGroup](s.ResourceIndexer, namespace)}
}

// HAChassisGroupNamespaceLister helps list and get HAChassisGroups.
// All objects returned here must be treated as read-only.
type HAChassisGroupNamespaceLister interface {
	// List lists all HAChassisGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.HAChassisGroup, err error)
	// Get retrieves the HAChassisGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*multiovnv1.HAChassisGroup, error)
	HAChassisGroupNamespaceListerExpansion
}

// hAChassisGroupNamespaceLister implements the HAChassisGroupNamespaceLister
// interface.
type hAChassisGroupNamespaceLister struct {
	listers.ResourceIndexer[*multiovnv1.HAChassisGroup]
}
