/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// HAChassisLister helps list HAChassises.
// All objects returned here must be treated as read-only.
type HAChassisLister interface {
	// List lists all HAChassises in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.HAChassis, err error)
	// HAChassises returns an object that can list and get HAChassises.
	HAChassises(namespace string) HAChassisNamespaceLister
	HAChassisListerExpansion
}

// hAChassisLister implements the HAChassisLister interface.
type hAChassisLister struct {
	listers.ResourceIndexer[*multiovnv1.HAChassis]
}

// NewHAChassisLister returns a new HAChassisLister.
func NewHAChassisLister(indexer cache.Indexer) HAChassisLister {
	return &hAChassisLister{listers.New[*multiovnv1.HAChassis](indexer, multiovnv1.Resource("hachassis"))}
}

// HAChassises returns an object that can list and get HAChassises.
func (s *hAChassisLister) HAChassises(namespace string) HAChassisNamespaceLister {
	return hAChassisNamespaceLister{listers.NewNamespaced[*multiovnv1.HAChassis](s.ResourceIndexer, namespace)}
}

// HAChassisNamespaceLister helps list and get HAChassises.
// All objects returned here must be treated as read-only.
type HAChassisNamespaceLister interface {
	// List lists all HAChassises in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.HAChassis, err error)
	// Get retrieves the HAChassis from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*multiovnv1.HAChassis, error)
	HAChassisNamespaceListerExpansion
}

// hAChassisNamespaceLister implements the HAChassisNamespaceLister
// interface.
type hAChassisNamespaceLister struct {
	listers.ResourceIndexer[*multiovnv1.HAChassis]
}
