/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LogicalSwitchPortLister helps list LogicalSwitchPorts.
// All objects returned here must be treated as read-only.
type LogicalSwitchPortLister interface {
	// List lists all LogicalSwitchPorts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.LogicalSwitchPort, err error)
	// LogicalSwitchPorts returns an object that can list and get LogicalSwitchPorts.
	LogicalSwitchPorts(namespace string) LogicalSwitchPortNamespaceLister
	LogicalSwitchPortListerExpansion
}

// logicalSwitchPortLister implements the LogicalSwitchPortLister interface.
type logicalSwitchPortLister struct {
	listers.ResourceIndexer[*multiovnv1.LogicalSwitchPort]
}

// NewLogicalSwitchPortLister returns a new LogicalSwitchPortLister.
func NewLogicalSwitchPortLister(indexer cache.Indexer) LogicalSwitchPortLister {
	return &logicalSwitchPortLister{listers.New[*multiovnv1.LogicalSwitchPort](indexer, multiovnv1.Resource("logicalswitchport"))}
}

// LogicalSwitchPorts returns an object that can list and get LogicalSwitchPorts.
func (s *logicalSwitchPortLister) LogicalSwitchPorts(namespace string) LogicalSwitchPortNamespaceLister {
	return logicalSwitchPortNamespaceLister{listers.NewNamespaced[*multiovnv1.LogicalSwitchPort](s.ResourceIndexer, namespace)}
}

// LogicalSwitchPortNamespaceLister helps list and get LogicalSwitchPorts.
// All objects returned here must be treated as read-only.
type LogicalSwitchPortNamespaceLister interface {
	// List lists all LogicalSwitchPorts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.LogicalSwitchPort, err error)
	// Get retrieves the LogicalSwitchPort from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*multiovnv1.LogicalSwitchPort, error)
	LogicalSwitchPortNamespaceListerExpansion
}

// logicalSwitchPortNamespaceLister implements the LogicalSwitchPortNamespaceLister
// interface.
type logicalSwitchPortNamespaceLister struct {
	listers.ResourceIndexer[*multiovnv1.LogicalSwitchPort]
}
