/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LogicalSwitchLister helps list LogicalSwitches.
// All objects returned here must be treated as read-only.
type LogicalSwitchLister interface {
	// List lists all LogicalSwitches in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.LogicalSwitch, err error)
	// LogicalSwitches returns an object that can list and get LogicalSwitches.
	LogicalSwitches(namespace string) LogicalSwitchNamespaceLister
	LogicalSwitchListerExpansion
}

// logicalSwitchLister implements the LogicalSwitchLister interface.
type logicalSwitchLister struct {
	listers.ResourceIndexer[*multiovnv1.LogicalSwitch]
}

// NewLogicalSwitchLister returns a new LogicalSwitchLister.
func NewLogicalSwitchLister(indexer cache.Indexer) LogicalSwitchLister {
	return &logicalSwitchLister{listers.New[*multiovnv1.LogicalSwitch](indexer, multiovnv1.Resource("logicalswitch"))}
}

// LogicalSwitches returns an object that can list and get LogicalSwitches.
func (s *logicalSwitchLister) LogicalSwitches(namespace string) LogicalSwitchNamespaceLister {
	return logicalSwitchNamespaceLister{listers.NewNamespaced[*multiovnv1.LogicalSwitch](s.ResourceIndexer, namespace)}
}

// LogicalSwitchNamespaceLister helps list and get LogicalSwitches.
// All objects returned here must be treated as read-only.
type LogicalSwitchNamespaceLister interface {
	// List lists all LogicalSwitches in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.LogicalSwitch, err error)
	// Get retrieves the LogicalSwitch from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*multiovnv1.LogicalSwitch, error)
	LogicalSwitchNamespaceListerExpansion
}

// logicalSwitchNamespaceLister implements the LogicalSwitchNamespaceLister
// interface.
type logicalSwitchNamespaceLister struct {
	listers.ResourceIndexer[*multiovnv1.LogicalSwitch]
}
