/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LogicalRouterPortLister helps list LogicalRouterPorts.
// All objects returned here must be treated as read-only.
type LogicalRouterPortLister interface {
	// List lists all LogicalRouterPorts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.LogicalRouterPort, err error)
	// LogicalRouterPorts returns an object that can list and get LogicalRouterPorts.
	LogicalRouterPorts(namespace string) LogicalRouterPortNamespaceLister
	LogicalRouterPortListerExpansion
}

// logicalRouterPortLister implements the LogicalRouterPortLister interface.
type logicalRouterPortLister struct {
	listers.ResourceIndexer[*multiovnv1.LogicalRouterPort]
}

// NewLogicalRouterPortLister returns a new LogicalRouterPortLister.
func NewLogicalRouterPortLister(indexer cache.Indexer) LogicalRouterPortLister {
	return &logicalRouterPortLister{listers.New[*multiovnv1.LogicalRouterPort](indexer, multiovnv1.Resource("logicalrouterport"))}
}

// LogicalRouterPorts returns an object that can list and get LogicalRouterPorts.
func (s *logicalRouterPortLister) LogicalRouterPorts(namespace string) LogicalRouterPortNamespaceLister {
	return logicalRouterPortNamespaceLister{listers.NewNamespaced[*multiovnv1.LogicalRouterPort](s.ResourceIndexer, namespace)}
}

// LogicalRouterPortNamespaceLister helps list and get LogicalRouterPorts.
// All objects returned here must be treated as read-only.
type LogicalRouterPortNamespaceLister interface {
	// List lists all LogicalRouterPorts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.LogicalRouterPort, err error)
	// Get retrieves the LogicalRouterPort from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*multiovnv1.LogicalRouterPort, error)
	LogicalRouterPortNamespaceListerExpansion
}

// logicalRouterPortNamespaceLister implements the LogicalRouterPortNamespaceLister
// interface.
type logicalRouterPortNamespaceLister struct {
	listers.ResourceIndexer[*multiovnv1.LogicalRouterPort]
}
