/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NatLister helps list Nats.
// All objects returned here must be treated as read-only.
type NatLister interface {
	// List lists all Nats in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.Nat, err error)
	// Nats returns an object that can list and get Nats.
	Nats(namespace string) NatNamespaceLister
	NatListerExpansion
}

// natLister implements the NatLister interface.
type natLister struct {
	listers.ResourceIndexer[*multiovnv1.Nat]
}

// NewNatLister returns a new NatLister.
func NewNatLister(indexer cache.Indexer) NatLister {
	return &natLister{listers.New[*multiovnv1.Nat](indexer, multiovnv1.Resource("nat"))}
}

// Nats returns an object that can list and get Nats.
func (s *natLister) Nats(namespace string) NatNamespaceLister {
	return natNamespaceLister{listers.NewNamespaced[*multiovnv1.Nat](s.ResourceIndexer, namespace)}
}

// NatNamespaceLister helps list and get Nats.
// All objects returned here must be treated as read-only.
type NatNamespaceLister interface {
	// List lists all Nats in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.Nat, err error)
	// Get retrieves the Nat from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*multiovnv1.Nat, error)
	NatNamespaceListerExpansion
}

// natNamespaceLister implements the NatNamespaceLister
// interface.
type natNamespaceLister struct {
	listers.ResourceIndexer[*multiovnv1.Nat]
}
