/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	multiovnv1 "github.com/multiovn/multi-ovn/pkg/apis/multiovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PortGroupPortLister helps list PortGroupPorts.
// All objects returned here must be treated as read-only.
type PortGroupPortLister interface {
	// List lists all PortGroupPorts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.PortGroupPort, err error)
	// PortGroupPorts returns an object that can list and get PortGroupPorts.
	PortGroupPorts(namespace string) PortGroupPortNamespaceLister
	PortGroupPortListerExpansion
}

// portGroupPortLister implements the PortGroupPortLister interface.
type portGroupPortLister struct {
	listers.ResourceIndexer[*multiovnv1.PortGroupPort]
}

// NewPortGroupPortLister returns a new PortGroupPortLister.
func NewPortGroupPortLister(indexer cache.Indexer) PortGroupPortLister {
	return &portGroupPortLister{listers.New[*multiovnv1.PortGroupPort](indexer, multiovnv1.Resource("portgroupport"))}
}

// PortGroupPorts returns an object that can list and get PortGroupPorts.
func (s *portGroupPortLister) PortGroupPorts(namespace string) PortGroupPortNamespaceLister {
	return portGroupPortNamespaceLister{listers.NewNamespaced[*multiovnv1.PortGroupPort](s.ResourceIndexer, namespace)}
}

// PortGroupPortNamespaceLister helps list and get PortGroupPorts.
// All objects returned here must be treated as read-only.
type PortGroupPortNamespaceLister interface {
	// List lists all PortGroupPorts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiovnv1.PortGroupPort, err error)
	// Get retrieves the PortGroupPort from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*multiovnv1.PortGroupPort, error)
	PortGroupPortNamespaceListerExpansion
}

// portGroupPortNamespaceLister implements the PortGroupPortNamespaceLister
// interface.
type portGroupPortNamespaceLister struct {
	listers.ResourceIndexer[*multiovnv1.PortGroupPort]
}
